server:
  port: 9092
spring:
  application:
    name: mcp-client
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-client
        version: 1.0.0
        type: ASYNC
        streamable-http:
          connections:
            mcp-server:
              url: http://localhost:9091
              endpoint: /mcp
    deepseek:
      base-url: https://api.deepseek.com
      api-key: YOUR-API-KEY
      chat:
        options:
          model: deepseek-chat
